### ISSUE TITLE
How to add this library to a project

### ISSUE THREAD

**Issue by Odomontois** [koka-community/std#16]
Hi! Installed Koka today.
How to actually use this library in my koka project (which is just a directory with bunch of `.kk` files)

**Comment by Ki11erRabbit** [comment]
It is quite simple. You just need to clone the repository somewhere then give the Koka compiler the flag `--include=<lib dir>` with `<lib dir>` being the path to the community stdlib. 
I hope this was helpful.

**Comment by TimWhiting** [comment]
Short flag is `-i/path/to/lib`
